#!/usr/bin/env zsh -f


# Much credit to github.com/mathiasbynens/dotfiles
# And to many others who also credit him

###############################################################################
# ASSIGN SOME VARIABLES                                                       #
###############################################################################

# This dir
FRESHMAC=$HOME/fresh-mac

# This script
INSTALL=$FRESHMAC/install

# All other scripts
MACOS=$FRESHMAC/.dotbin/.macOS
HOMEBREW=$FRESHMAC/.dotbin/.homebrew
BREWAPPS=$FRESHMAC/.dotbin/.brewapps
CLEANBREW=$FRESHMAC/.dotbin/.cleanbrew
OMZ=$FRESHMAC/.dotbin/.omz
TODO=$FRESHMAC/.dotbin/.todo


###############################################################################
# LOAD THE MENU                                                               #
###############################################################################

# Clear the screen
clear && printf '\e[3J'

# Ask for the administrator password upfront and run a keep-alive
# to update existing `sudo` time stamp until script has finished
sudo -v
while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &

while :
do
    clear
    cat<<EOF

    ########################################################################
    #                                                                      #
    #                            fresh-mac                                 #
    #                                                                      #
    ########################################################################
    #                                                                      #
    #     Execute each task in order after a fresh macOS install           #
    #                                                                      #
    #     Enter your choice:                                               #
    #                                                                      #
    #        (1) Change Mac default preferences                            #
    #        (2) Install Homebrew                                          #
    #        (3) Install apps with Homebrew                                #
    #        (4) Clean up Homebrew                                         #
    #        (5) Install Oh-My-Zsh                                         #
    #        (6) Read the post-run TODO list                               #
    #                                                                      #
    #        (0) Exit                                                      #
    #                                                                      #
    ########################################################################
EOF
    read -n1 -s
    case "$REPLY" in
    "1")  echo "Customizing your Mac!"                | . $MACOS           ;;
    "2")  echo "Installing Homebrew!"                 | . $HOMEBREW        ;;
    "3")  echo "Installing a bunch of apps!"          | . $BREWAPPS        ;;
    "4")  echo "Updating & cleaning up Homebrew!"     | . $CLEANBREW       ;;
    "5")  echo "Installing Oh My Zsh!"                | . $OMZ             ;;
    "6")  echo "Stuff TO DO!"                         | . $TODO            ;;
    "0")  exit                                                             ;;
     * )  echo "Invalid option!"                                           ;;
    esac
done
