#!/usr/bin/env zsh -f


# Much credit to github.com/mathiasbynens/dotfiles

###############################################################################

FRESHMAC=$HOME/fresh-mac

MACOS=$FRESHMAC/dotbin/.macOS
HOMEBREW=$FRESHMAC/dotbin/.homebrew
BREWAPPS=$FRESHMAC/dotbin/.brewapps
OMZ=$FRESHMAC/dotbin/.omz
CLEANBREW=$FRESHMAC/dotbin/.cleanbrew
TODO=$FRESHMAC/dotbin/.todo
INSTALL=$FRESHMAC/install

###############################################################################

while :
do
    clear
    cat<<EOF

    ########################################################################
    #                                                                      #
    #                            fresh-mac                                 #
    #                                                                      #
    ########################################################################
    #                                                                      #
    #     Execute each task in order after a fresh macOS install           #
    #                                                                      #
    #     Enter your choice:                                               #
    #                                                                      #
    #        (1) Customize Mac preferences                                 #
    #        (2) Install Homebrew                                          #
    #        (3) Install apps with Homebrew                                #
    #        (4) Install Oh-My-Zsh                                         #
    #        (5) Clean up Homebrew                                         #
    #        (6) Read to TODO list when finished                           #
    #                                                                      #
    #        (0) Exit                                                      #
    #                                                                      #
    ########################################################################
EOF
    read -n1 -s
    case "$REPLY" in
    "1")  echo "Tweaking Mac config..."              | . $MACOS           ;;
    "2")  echo "Installing Homebrew..."              | . $HOMEBREW        ;;
    "3")  echo "Installing a bunch of apps..."       | . $BREWAPPS        ;;
    "4")  echo "Installing Oh My Zsh..."             | . $OMZ             ;;
    "5")  echo "Updating & cleaning up Homebrew..."  | . $CLEANBREW       ;;
    "6")  echo "Stuff TO DO!..."                     | . $TODO            ;;
    "0")  exit                                                            ;;
     * )  echo "Invalid option!"                                          ;;
    esac
    sleep 1
done
