#!/usr/bin/env zsh -f

# Much credit to github.com/mathiasbynens/dotfiles


###############################################################################

FRESHMAC=$HOME/fresh-mac

MACOS=$FRESHMAC/dotbin/.macOS
HOMEBREW=$FRESHMAC/dotbin/.homebrew
BREWAPPS=$FRESHMAC/dotbin/.brewapps
OMZ=$FRESHMAC/dotbin/.omz
CLEANBREW=$FRESHMAC/dotbin/.cleanbrew
INSTALL=$FRESHMAC/install

###############################################################################

while :
do
    clear
    cat<<EOF

    ########################################################################
    #                                                                      #
    #                            fresh-mac                                 #
    #                                                                      #
    ########################################################################
    #                                                                      #
    #     Execute each task in order after a fresh macOS install           #
    #                                                                      #
    #     Enter your choice:                                               #
    #                                                                      #
    #        (1) Customize Mac preferences                                 #
    #        (2) Install Homebrew                                          #
    #        (3) Install apps with Homebrew                                #
    #        (4) Install Oh-My-Zsh                                         #
    #        (5) Clean up Homebrew                                         #
    #                                                                      #
    #        (0) Exit                                                      #
    #                                                                      #
    ########################################################################
EOF
    read -n1 -s
    case "$REPLY" in
    "1")  echo "Tweaking Mac config..."              | . $MACOS           ;;
    "2")  echo "Installing Homebrew..."              | . $HOMEBREW        ;;
    "3")  echo "Installing a bunch of apps..."       | . $BREWAPPS        ;;
    "4")  echo "Installing Oh My Zsh..."             | . $OMZ             ;;
    "5")  echo "Updating & cleaning up Homebrew..."  | . $CLEANBREW       ;;
    "0")  exit                                                            ;;
     * )  echo "Invalid option!"                                          ;;
    esac
    sleep 1
done

###############################################################################
#   Now finish up with a couple of simple tasks and a friendly reminder       #
###############################################################################

# Clear the screen
clear && printf '\e[3J'

# Announce that we're finished but there are more tasks, using colors
echo "
\033[1;93m
FINISHED! (Almost)
\033[0m
"
sleep 2
echo "\033[;92m
Remember, you have a \033[1;93mTODO\033[0m \033[;92mlist now:\033[0m
"
sleep 2
echo "  • \033[;92mRestore\033[0m \033[1;93mPreferences\033[0m \033[;92mfrom your backup\033[0m"
sleep 1
echo "  • \033[;92mInstall \033[1;93mDropbox\033[0m \033[;92mand then run\033[0m 'mackup restore'"
sleep 1
echo "  • \033[1;91mLogout\033[0m \033[;92mor\033[0m \033[1;91mrestart
\033[0m
"

read -p "Press enter to continue"
